# Generated by Django 4.1.7 on 2023-03-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=512)),
                ('tel_number', models.CharField(max_length=10)),
                ('salt', models.CharField(default=None, max_length=512)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=40)),
                ('information', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('information', models.CharField(max_length=1000000)),
                ('released', models.DateField()),
                ('image', models.ImageField(upload_to='static/image')),
                ('availability', models.BooleanField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='pre_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.game')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('reviews', models.CharField(max_length=1000000)),
                ('created', models.DateField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pre_order')),
            ],
        ),
        migrations.CreateModel(
            name='payment_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=40)),
                ('card_date', models.DateField()),
                ('name_surname', models.CharField(max_length=80)),
                ('cvv_code', models.CharField(max_length=512)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('compleate', models.BooleanField(default=0)),
                ('card_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.payment_card')),
                ('num_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pre_order')),
            ],
        ),
    ]
