# Generated by Django 4.1.7 on 2023-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_buyer_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
