# Generated by Django 4.1.7 on 2023-04-03 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='information',
            field=models.JSONField(max_length=100000000),
        ),
        migrations.CreateModel(
            name='slider_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.game')),
            ],
        ),
    ]
