# Generated by Django 4.1.7 on 2023-04-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_game_information_slider_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='information',
            field=models.CharField(max_length=100000000),
        ),
    ]
