# Generated by Django 4.1.7 on 2023-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_slider_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_photo',
            name='photo',
            field=models.ImageField(upload_to='photo/None'),
        ),
    ]
