# Generated by Django 4.1.7 on 2023-04-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_slider_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider_photo',
            old_name='game',
            new_name='games',
        ),
        migrations.AlterField(
            model_name='slider_photo',
            name='photo',
            field=models.ImageField(upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x000002995880F190>'),
        ),
    ]
