# Generated by Django 4.1.7 on 2023-04-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_game_slider_photo_games_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_photo',
            name='photo',
            field=models.ImageField(upload_to='photos/<django.db.models.query_utils.DeferredAttribute object at 0x0000018734E3EC80>'),
        ),
    ]
