# Generated by Django 4.1.7 on 2023-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_slider_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider_photo',
            old_name='games',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='slider_photo',
            name='photo',
            field=models.ImageField(upload_to='photo/None'),
        ),
    ]
