# Generated by Django 4.1.7 on 2023-04-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_slider_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='shop.buyer'),
            preserve_default=False,
        ),
    ]
