# Generated by Django 4.1.7 on 2023-05-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_order',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='shop.buyer'),
            preserve_default=False,
        ),
    ]
