# Generated by Django 4.1.7 on 2023-05-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_pre_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_order',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.order'),
        ),
    ]
