# Generated by Django 4.1.7 on 2023-05-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.game'),
        ),
    ]
