# Generated by Django 4.1.7 on 2023-05-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_reviews_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='game_id',
            new_name='games',
        ),
    ]
