# Generated by Django 4.1.7 on 2023-05-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_game_id_reviews_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='games',
            new_name='game_id',
        ),
    ]
