# Generated by Django 4.1.7 on 2023-05-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rename_games_reviews_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.DateField(default=None, null=True),
        ),
    ]
