# Generated by Django 4.1.7 on 2023-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_buyer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_superuser',
            field=models.BooleanField(default=0),
        ),
    ]
